wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1660503663
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      4: 3.9.12
      5: 0.12.17
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.023726239123113543
model:
  desc: null
  value: ResNet50
task:
  desc: null
  value: Classification B Quality
weight_decay:
  desc: null
  value: 0.005
