wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0
epochs:
  value: 20
learning_rate:
  value: 0.05751798530520684
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.0005
