wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3
epochs:
  value: 20
learning_rate:
  value: 0.06648503342630165
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.05
