wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 20
learning_rate:
  value: 0.09198221171071733
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.005
