wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0
epochs:
  value: 20
learning_rate:
  value: 0.02543523698918703
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.05
