wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
epochs:
  value: 20
learning_rate:
  value: 0.03230991466352997
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.0005
