wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0
epochs:
  value: 30
learning_rate:
  value: 0.02144043848945012
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.005
