wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0
epochs:
  value: 10
learning_rate:
  value: 0.006998213765943347
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.0005
