wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5
epochs:
  value: 10
learning_rate:
  value: 0.07042309053979288
model:
  value: ResNet50
task:
  value: Classification B Quality
weight_decay:
  value: 0.05
